import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./_providers/providers";

export const metadata: Metadata = {
  title: "CAPOASA",
  description: "Generated by create next app",
};

// 🎯 Audit d'accessibilité automatique
if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
  import('@axe-core/react').then((axe) => {
    const React = require('react');
    const ReactDOM = require('react-dom');
    axe.default(React, ReactDOM, 1000);
  });
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}