import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./_providers/providers";

export const metadata: Metadata = {
  title: "CAPOASA",
  description: "Generated by create next app",
};

// 🎯 Audit d'accessibilité automatique
if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
  import('@axe-core/react').then((axe) => {
    const React = require('react');
    const ReactDOM = require('react-dom');
    axe.default(React, ReactDOM, 1000);
  });
}

import NextTopLoader from 'nextjs-toploader';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en" suppressHydrationWarning>
      <body>
        <NextTopLoader color="#2299DD" initialPosition={0.08} crawlSpeed={200} height={3} crawl={true} showSpinner={false} easing="ease" speed={200} shadow="0 0 10px #2299DD,0 0 5px #2299DD" />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}